"""Procedural NMS system/region name generation — shared service.

Wraps the vendored `nms_namegen` library so every caller generates names the
same way: the `/api/namegen` endpoint, the `/api/glyph/preview` convenience
endpoint, and the `/api/extraction` server-side name safety net. Callers get
back `(None, None)` when the library is unavailable or the glyph is malformed,
so they can degrade gracefully instead of 500-ing.

This is the same logic the in-game extractor and the web wizard rely on, made
reusable so the Keeper Discord bot can mirror their auto-naming via one HTTP
call rather than re-implementing the algorithm.
"""
import json
import logging
import re
from pathlib import Path

logger = logging.getLogger('control.room')

# backend/services/ -> backend/ -> data/galaxies.json
_GALAXIES_PATH = Path(__file__).parent.parent / 'data' / 'galaxies.json'
_galaxy_to_idx_cache = None

# Names auto-generated by clients that should be REPLACED with the real
# procedural name when the safety net sees them:
#   - "System_<glyph>"     : the /api/extraction default when no name is sent.
#   - "[TAG] X#-XXXX"       : the Keeper bot's generate_system_name() placeholder
#                            ({star[0]}{conflict}-{glyph[-4:]}).
# The Keeper regex is deliberately tight (bracketed tag, single space, a single
# letter + single digit, dash, exactly four hex chars) so civ-tag-PREFIXED REAL
# names like "[RES]Boulde" (no space, not the Letter-Digit-Hex4 shape) are never
# mistaken for placeholders and clobbered.
_KEEPER_AUTONAME_RE = re.compile(r'^\[[^\]]{1,8}\]\s[A-Za-z]\d-[0-9A-Fa-f]{4}$')


def galaxy_name_to_index(galaxy_name):
    """Resolve a galaxy display name (e.g. 'Euclid') to its numeric index.

    Unknown names fall back to 0 (Euclid), matching the legacy /api/namegen
    behavior.
    """
    global _galaxy_to_idx_cache
    if _galaxy_to_idx_cache is None:
        try:
            with open(_GALAXIES_PATH, encoding='utf-8') as f:
                galaxies = json.load(f)
            _galaxy_to_idx_cache = {v: int(k) for k, v in galaxies.items()}
        except Exception:
            _galaxy_to_idx_cache = {'Euclid': 0}
    return _galaxy_to_idx_cache.get(galaxy_name or 'Euclid', 0)


def generate_names(glyph_code, galaxy_name='Euclid'):
    """Return (system_name, region_name) for a 12-char glyph + galaxy NAME.

    Returns (None, None) if the glyph is malformed or `nms_namegen` is missing,
    so callers can decide whether to 503, fall back, or simply skip.
    """
    if not glyph_code or len(glyph_code) != 12:
        return None, None
    try:
        portal_code = int(glyph_code, 16)
    except (ValueError, TypeError):
        return None, None

    galaxy_idx = galaxy_name_to_index(galaxy_name)
    try:
        from nms_namegen.system import systemName
        from nms_namegen.region import regionName
        return systemName(portal_code, galaxy_idx), regionName(portal_code, galaxy_idx)
    except ImportError:
        logger.warning("nms_namegen not available; cannot generate procedural names")
        return None, None
    except Exception as e:
        logger.error(f"Name generation failed for glyph={glyph_code} galaxy={galaxy_name}: {e}")
        return None, None


def looks_like_placeholder_name(name):
    """True if `name` is blank or a client auto-generated placeholder that should
    be replaced by the real procedural name (see _KEEPER_AUTONAME_RE)."""
    if not name or not str(name).strip():
        return True
    n = str(name).strip()
    if n.startswith('System_'):
        return True
    if _KEEPER_AUTONAME_RE.match(n):
        return True
    return False
